from glossary.crafting.craftable import Craftable
from glossary.items.weapons import weapons
from glossary.items.miscellaneous import miscellaneous
from glossary.items.tools import tools
from glossary.items.boards import boards
from glossary.items.reagents import reagents
from utils.gumps import GumpSelection

carpName = "Carpentry"
carpGump = 949095101
carpTools = [
    tools["dovetail saw"],
    tools["draw knife"],
    tools["froe"],
    tools["hammer"],
    tools["inshave"],
    tools["jointing plane"],
    tools["moulding planes"],
    tools["nails"],
    tools["saw"],
    tools["scorp"],
    tools["smoothing plane"],
]


carpCraftables = {
    ### Other: Gump Button 1 ###
    "trash barrel": Craftable(
        Name="trash barrel",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 42.6},
        ResourcesNeeded={"boards": 50},
        GumpPath=(GumpSelection(carpGump, 1), GumpSelection(carpGump, 2)),
    ),
    "blank scroll": Craftable(
        Name="blank scroll",
        Item=miscellaneous["blank scroll"],
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 70.0, "Inscription": 45.0},
        ResourcesNeeded={boards["ordinary board"]: 1, reagents["Spider's Silk"]: 1},
        GumpPath=(GumpSelection(carpGump, 1), GumpSelection(carpGump, 9)),
    ),
    "barrel staves": Craftable(
        Name="barrel staves",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 0.0},
        ResourcesNeeded={"boards": 5},
        GumpPath=(GumpSelection(carpGump, 1), GumpSelection(carpGump, 16)),
    ),
    "barrel lid": Craftable(
        Name="barrel lid",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 11.0},
        ResourcesNeeded={"boards": 4},
        GumpPath=(GumpSelection(carpGump, 1), GumpSelection(carpGump, 23)),
    ),
    "short music stand (left)": Craftable(
        Name="short music stand (left)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 78.9},
        ResourcesNeeded={"boards": 15},
        GumpPath=(GumpSelection(carpGump, 1), GumpSelection(carpGump, 30)),
    ),
    "tall music stand (left)": Craftable(
        Name="tall music stand (left)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 81.5},
        ResourcesNeeded={"boards": 20},
        GumpPath=(GumpSelection(carpGump, 1), GumpSelection(carpGump, 37)),
    ),
    "easel (south)": Craftable(
        Name="easel (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 86.8},
        ResourcesNeeded={"boards": 20},
        GumpPath=(GumpSelection(carpGump, 1), GumpSelection(carpGump, 44)),
    ),
    ### Misc. Add-Ons: Gump Button 8 ###
    "small bed (south)": Craftable(
        Name="small bed (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 94.7, "Tailoring": 75.0},
        ResourcesNeeded={"boards": 100, "cloth": 100},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 2)),
    ),
    "small bed (east)": Craftable(
        Name="small bed (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 94.7, "Tailoring": 75.0},
        ResourcesNeeded={"boards": 100, "cloth": 100},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 9)),
    ),
    "large bed (south)": Craftable(
        Name="large bed (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 94.7, "Tailoring": 75.0},
        ResourcesNeeded={"boards": 150, "cloth": 150},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 16)),
    ),
    "large bed (east)": Craftable(
        Name="large bed (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 94.7, "Tailoring": 75.0},
        ResourcesNeeded={"boards": 150, "cloth": 150},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 23)),
    ),
    "dartboard (south)": Craftable(
        Name="dartboard (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 15.7},
        ResourcesNeeded={"boards": 5},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 30)),
    ),
    "dartboard (east)": Craftable(
        Name="dartboard (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 15.7},
        ResourcesNeeded={"boards": 5},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 37)),
    ),
    "bulletin board (east)": Craftable(
        Name="bulletin board (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 85.0},
        ResourcesNeeded={"boards": 200},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 44)),
    ),
    "bulletin board (south)": Craftable(
        Name="bulletin board (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 85.0},
        ResourcesNeeded={"boards": 200},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 51)),
    ),
    "ballot box": Craftable(
        Name="ballot box",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 47.3},
        ResourcesNeeded={"boards": 5},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 58)),
    ),
    "pentagram": Craftable(
        Name="pentagram",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 100.0, "Magery": 75.0},
        ResourcesNeeded={"boards": 100, "ingots": 40},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 65)),
    ),
    "abbatoir": Craftable(
        Name="abbatoir",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 100.0, "Magery": 50.0},
        ResourcesNeeded={"boards": 100, "ingots": 40},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 72)),
    ),
    "stone abbatoir": Craftable(
        Name="stone abbatoir",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 115.0, "Magery": 100.0},
        ResourcesNeeded={"boards": 500, "ingots": 500},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 79)),
    ),
    "training dummy (east)": Craftable(
        Name="training dummy (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 68.4, "Tailoring": 50.0},
        ResourcesNeeded={"boards": 55, "cloth": 60},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 2)),
    ),
    "training dummy (south)": Craftable(
        Name="training dummy (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 68.4, "Tailoring": 50.0},
        ResourcesNeeded={"boards": 55, "cloth": 60},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 9)),
    ),
    "pickpocket dip (east)": Craftable(
        Name="pickpocket dip (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 73.6, "Tailoring": 50.0},
        ResourcesNeeded={"boards": 65, "cloth": 60},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 16)),
    ),
    "pickpocket dip (south)": Craftable(
        Name="pickpocket dip (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 73.6, "Tailoring": 50.0},
        ResourcesNeeded={"boards": 65, "cloth": 60},
        GumpPath=(GumpSelection(carpGump, 8), GumpSelection(carpGump, 23)),
    ),
    ### Furniture: Gump Button 15 ###
    "foot stool": Craftable(
        Name="foot stool",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 11.0},
        ResourcesNeeded={"boards": 9},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 2)),
    ),
    "stool": Craftable(
        Name="stool",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 11.0},
        ResourcesNeeded={"boards": 9},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 9)),
    ),
    "straw chair": Craftable(
        Name="straw chair",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 21.0},
        ResourcesNeeded={"boards": 13},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 16)),
    ),
    "wooden chair": Craftable(
        Name="wooden chair",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 21.0},
        ResourcesNeeded={"boards": 13},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 23)),
    ),
    "Vesper-style chair": Craftable(
        Name="Vesper-style chair",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 42.1},
        ResourcesNeeded={"boards": 15},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 30)),
    ),
    "Trinsic-style chair": Craftable(
        Name="Trinsic-style chair",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 42.1},
        ResourcesNeeded={"boards": 13},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 37)),
    ),
    "wooden bench": Craftable(
        Name="wooden bench",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 52.6},
        ResourcesNeeded={"boards": 17},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 44)),
    ),
    "wooden throne": Craftable(
        Name="wooden throne",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 52.6},
        ResourcesNeeded={"boards": 17},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 51)),
    ),
    "Magnicia-style throne": Craftable(
        Name="Magnicia-style throne",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 73.6},
        ResourcesNeeded={"boards": 19},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 58)),
    ),
    "small table": Craftable(
        Name="small table",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 42.1},
        ResourcesNeeded={"boards": 17},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 65)),
    ),
    "writing table": Craftable(
        Name="writing table",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 63.1},
        ResourcesNeeded={"boards": 17},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 72)),
    ),
    "large table": Craftable(
        Name="large table",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 63.1},
        ResourcesNeeded={"boards": 23},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 79)),
    ),
    "Yew wood table": Craftable(
        Name="Yew wood table",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 84.2},
        ResourcesNeeded={"boards": 27},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 86)),
    ),
    "elegant low table": Craftable(
        Name="elegant low table",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 80.0},
        ResourcesNeeded={"boards": 35},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 93)),
    ),
    "plain low table": Craftable(
        Name="plain low table",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 80.0},
        ResourcesNeeded={"boards": 35},
        GumpPath=(GumpSelection(carpGump, 15), GumpSelection(carpGump, 100)),
    ),
    ### Containers: Gump Button 22 ###
    "wooden box": Craftable(
        Name="wooden box",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 21.0},
        ResourcesNeeded={"boards": 10},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 2)),
    ),
    "small crate": Craftable(
        Name="small crate",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 10.0},
        ResourcesNeeded={"boards": 8},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 9)),
    ),
    "medium crate": Craftable(
        Name="medium crate",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 31.0},
        ResourcesNeeded={"boards": 15},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 16)),
    ),
    "large crate": Craftable(
        Name="large crate",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 47.3},
        ResourcesNeeded={"boards": 18},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 23)),
    ),
    "wooden chest": Craftable(
        Name="wooden chest",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 73.6},
        ResourcesNeeded={"boards": 20},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 30)),
    ),
    "wooden shelf": Craftable(
        Name="wooden shelf",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 31.5},
        ResourcesNeeded={"boards": 25},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 37)),
    ),
    "armoire (red)": Craftable(
        Name="armoire (red)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 84.2},
        ResourcesNeeded={"boards": 35},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 44)),
    ),
    "armoire": Craftable(
        Name="armoire",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 84.2},
        ResourcesNeeded={"boards": 35},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 51)),
    ),
    "treasure chest (silver)": Craftable(
        Name="treasure chest",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 110.0},
        ResourcesNeeded={
            "log": 200,
            "diamond": 100,
            "ruby": 100,
            "emerald": 100,
            "sapphire": 100,
            "forged metal": 5,
        },
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 58)),
    ),
    "treasure chest (silver and gold)": Craftable(
        Name="treasure chest",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 115.0},
        ResourcesNeeded={
            "log": 200,
            "diamond": 200,
            "ruby": 200,
            "emerald": 200,
            "sapphire": 200,
            "forged metal": 10,
        },
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 65)),
    ),
    "treasure chest (scrolls and potions)": Craftable(
        Name="treasure chest",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 115.0},
        ResourcesNeeded={
            "log": 200,
            "diamond": 200,
            "ruby": 200,
            "emerald": 200,
            "sapphire": 200,
            "forged metal": 10,
        },
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 72)),
    ),
    "gilded wooden chest": Craftable(
        Name="gilded wooden chest",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 120.0},
        ResourcesNeeded={"boards": 1000},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 79)),
    ),
    "gothic chest": Craftable(
        Name="gothic chest",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 100.0},
        ResourcesNeeded={"boards": 1000},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 86)),
    ),
    "ornate wooden chest": Craftable(
        Name="ornate wooden chest",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 120.0},
        ResourcesNeeded={"boards": 1000},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 93)),
    ),
    "wooden footlocker": Craftable(
        Name="wooden footlocker",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 120.0},
        ResourcesNeeded={"boards": 1000},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 100)),
    ),
    "finished wooden chest": Craftable(
        Name="finished wooden chest",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 120.0},
        ResourcesNeeded={"boards": 1000},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 107)),
    ),
    "short cabinet": Craftable(
        Name="short cabinet",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 120.0},
        ResourcesNeeded={"boards": 1000},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 114)),
    ),
    "tall cabinet": Craftable(
        Name="tall cabinet",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 120.0},
        ResourcesNeeded={"boards": 1000},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 121)),
    ),
    "plain wooden chest": Craftable(
        Name="plain wooden chest",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 90.0},
        ResourcesNeeded={"boards": 30},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 128)),
    ),
    "red armoire": Craftable(
        Name="red armoire",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 90.0},
        ResourcesNeeded={"boards": 40},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 135)),
    ),
    "elegant armoire": Craftable(
        Name="elegant armoire",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 90.0},
        ResourcesNeeded={"boards": 40},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 142)),
    ),
    "maple armoire": Craftable(
        Name="maple armoire",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 90.0},
        ResourcesNeeded={"boards": 40},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 149)),
    ),
    "cherry armoire": Craftable(
        Name="cherry armoire",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 90.0},
        ResourcesNeeded={"boards": 40},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 156)),
    ),
    "keg": Craftable(
        Name="keg",
        Item=None,
        RetainsMark=False,
        RetainsColor=False,
        MinSkill={"Carpentry": 57.8},
        ResourcesNeeded={"barrel staves": 3, "barrel hoops": 1, "barrel lid": 1},
        GumpPath=(GumpSelection(carpGump, 22), GumpSelection(carpGump, 163)),
    ),
    ### Weapons and Armor: Gump Button 29 ###
    "shepherd's crook": Craftable(
        Name="shepherd's crook",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 78.9},
        ResourcesNeeded={"boards": 7},
        GumpPath=(GumpSelection(carpGump, 29), GumpSelection(carpGump, 2)),
    ),
    "quarter staff": Craftable(
        Name="quarter staff",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 73.6},
        ResourcesNeeded={"boards": 6},
        GumpPath=(GumpSelection(carpGump, 29), GumpSelection(carpGump, 9)),
    ),
    "gnarled staff": Craftable(
        Name="gnarled staff",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 78.9},
        ResourcesNeeded={"boards": 7},
        GumpPath=(GumpSelection(carpGump, 29), GumpSelection(carpGump, 16)),
    ),
    "wooden shield": Craftable(
        Name="wooden shield",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 52.6},
        ResourcesNeeded={"boards": 9},
        GumpPath=(GumpSelection(carpGump, 29), GumpSelection(carpGump, 23)),
    ),
    "club": Craftable(
        Name="club",
        Item=weapons["club"],
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 28.2},
        ResourcesNeeded={boards["ordinary board"]: 6},
        GumpPath=(GumpSelection(carpGump, 29), GumpSelection(carpGump, 30)),
    ),
    "fishing pole": Craftable(
        Name="fishing pole",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 68.4, "Tailoring": 40.0},
        ResourcesNeeded={"boards": 5, "cloth": 5},
        GumpPath=(GumpSelection(carpGump, 29), GumpSelection(carpGump, 37)),
    ),
    ### Instruments: Gump Button 36 ###
    "lap harp": Craftable(
        Name="lap harp",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 63.1, "Musicianship": 45.0},
        ResourcesNeeded={"boards": 20, "cloth": 10},
        GumpPath=(GumpSelection(carpGump, 36), GumpSelection(carpGump, 2)),
    ),
    "standing harp": Craftable(
        Name="standing harp",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 78.9, "Musicianship": 45.0},
        ResourcesNeeded={"boards": 35, "cloth": 15},
        GumpPath=(GumpSelection(carpGump, 36), GumpSelection(carpGump, 9)),
    ),
    "drum": Craftable(
        Name="drum",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 57.8, "Musicianship": 45.0},
        ResourcesNeeded={"boards": 20, "cloth": 10},
        GumpPath=(GumpSelection(carpGump, 36), GumpSelection(carpGump, 16)),
    ),
    "lute": Craftable(
        Name="lute",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 68.4, "Musicianship": 45.0},
        ResourcesNeeded={"boards": 25, "cloth": 10},
        GumpPath=(GumpSelection(carpGump, 36), GumpSelection(carpGump, 23)),
    ),
    "tambourine": Craftable(
        Name="tambourine",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 57.8, "Musicianship": 45.0},
        ResourcesNeeded={"boards": 15, "cloth": 10},
        GumpPath=(GumpSelection(carpGump, 36), GumpSelection(carpGump, 30)),
    ),
    "tambourine (tassle)": Craftable(
        Name="tambourine (tassle)",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 57.8, "Musicianship": 45.0},
        ResourcesNeeded={"boards": 15, "cloth": 15},
        GumpPath=(GumpSelection(carpGump, 36), GumpSelection(carpGump, 37)),
    ),
    "bamboo flute": Craftable(
        Name="bamboo flute",
        Item=None,
        RetainsMark=True,
        RetainsColor=True,
        MinSkill={"Carpentry": 80.0, "Musicianship": 45.0},
        ResourcesNeeded={"boards": 15},
        GumpPath=(GumpSelection(carpGump, 36), GumpSelection(carpGump, 44)),
    ),
    ### Blacksmithing: Gump Button 43 ###
    "small forge": Craftable(
        Name="small forge",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 73.6, "Blacksmithing": 75.0},
        ResourcesNeeded={"boards": 5, "ingots": 75},
        GumpPath=(GumpSelection(carpGump, 43), GumpSelection(carpGump, 2)),
    ),
    "large forge (east)": Craftable(
        Name="large forge (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 78.9, "Blacksmithing": 80.0},
        ResourcesNeeded={"boards": 5, "ingots": 100},
        GumpPath=(GumpSelection(carpGump, 43), GumpSelection(carpGump, 9)),
    ),
    "large forge (south)": Craftable(
        Name="large forge (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 78.9, "Blacksmithing": 80.0},
        ResourcesNeeded={"boards": 5, "ingots": 100},
        GumpPath=(GumpSelection(carpGump, 43), GumpSelection(carpGump, 16)),
    ),
    "anvil (east)": Craftable(
        Name="anvil (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 73.6, "Blacksmithing": 75.0},
        ResourcesNeeded={"boards": 5, "ingots": 150},
        GumpPath=(GumpSelection(carpGump, 43), GumpSelection(carpGump, 23)),
    ),
    "anvil (south)": Craftable(
        Name="anvil (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 73.6, "Blacksmithing": 75.0},
        ResourcesNeeded={"boards": 5, "ingots": 150},
        GumpPath=(GumpSelection(carpGump, 43), GumpSelection(carpGump, 30)),
    ),
    ### Tailoring and Cooking: Gump Button 50 ###
    "spinning wheel (east)": Craftable(
        Name="spinning wheel (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 73.6, "Tailoring": 65.0},
        ResourcesNeeded={"boards": 75, "cloth": 25},
        GumpPath=(GumpSelection(carpGump, 50), GumpSelection(carpGump, 2)),
    ),
    "spinning wheel (south)": Craftable(
        Name="spinning wheel (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 73.6, "Tailoring": 65.0},
        ResourcesNeeded={"boards": 75, "cloth": 25},
        GumpPath=(GumpSelection(carpGump, 50), GumpSelection(carpGump, 9)),
    ),
    "loom (east)": Craftable(
        Name="loom (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 84.2, "Tailoring": 65.0},
        ResourcesNeeded={"boards": 85, "cloth": 25},
        GumpPath=(GumpSelection(carpGump, 50), GumpSelection(carpGump, 16)),
    ),
    "loom (south)": Craftable(
        Name="loom (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 84.2, "Tailoring": 65.0},
        ResourcesNeeded={"boards": 85, "cloth": 25},
        GumpPath=(GumpSelection(carpGump, 50), GumpSelection(carpGump, 23)),
    ),
    ### Cooking: Gump Button 57 ###
    "stone oven (east)": Craftable(
        Name="stone oven (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 68.4, "Tinkering": 50.0},
        ResourcesNeeded={"boards": 85, "ingots": 125},
        GumpPath=(GumpSelection(carpGump, 57), GumpSelection(carpGump, 2)),
    ),
    "stone oven (south)": Craftable(
        Name="stone oven (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 68.4, "Tinkering": 50.0},
        ResourcesNeeded={"boards": 85, "ingots": 125},
        GumpPath=(GumpSelection(carpGump, 57), GumpSelection(carpGump, 9)),
    ),
    "flour mill (east)": Craftable(
        Name="flour mill (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 94.7, "Tinkering": 50.0},
        ResourcesNeeded={"boards": 100, "ingots": 50},
        GumpPath=(GumpSelection(carpGump, 57), GumpSelection(carpGump, 16)),
    ),
    "flour mill (south)": Craftable(
        Name="flour mill (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 94.7, "Tinkering": 50.0},
        ResourcesNeeded={"boards": 100, "ingots": 50},
        GumpPath=(GumpSelection(carpGump, 57), GumpSelection(carpGump, 23)),
    ),
    "water trough (east)": Craftable(
        Name="water trough (east)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 94.7},
        ResourcesNeeded={"boards": 150},
        GumpPath=(GumpSelection(carpGump, 57), GumpSelection(carpGump, 30)),
    ),
    "water trough (south)": Craftable(
        Name="water trough (south)",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 94.7},
        ResourcesNeeded={"boards": 150},
        GumpPath=(GumpSelection(carpGump, 57), GumpSelection(carpGump, 37)),
    ),
    ### Boats: Gump Button 64 ###
    "small boat": Craftable(
        Name="small boat",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 81.6, "Tailoring": 75.0, "Lumberjacking": 75.0},
        ResourcesNeeded={"boards": 425, "cloth": 100},
        GumpPath=(GumpSelection(carpGump, 64), GumpSelection(carpGump, 2)),
    ),
    "small dragon boat": Craftable(
        Name="small dragon boat",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 83.0, "Tailoring": 75.0, "Lumberjacking": 75.0},
        ResourcesNeeded={"boards": 450, "cloth": 100},
        GumpPath=(GumpSelection(carpGump, 64), GumpSelection(carpGump, 9)),
    ),
    "medium boat": Craftable(
        Name="medium boat",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 84.6, "Tailoring": 80.0, "Lumberjacking": 80.0},
        ResourcesNeeded={"boards": 500, "cloth": 100},
        GumpPath=(GumpSelection(carpGump, 64), GumpSelection(carpGump, 16)),
    ),
    "medium dragon boat": Craftable(
        Name="meduim dragon boat",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 84.6, "Tailoring": 80.0, "Lumberjacking": 80.0},
        ResourcesNeeded={"boards": 500, "cloth": 100},
        GumpPath=(GumpSelection(carpGump, 64), GumpSelection(carpGump, 23)),
    ),
    "large boat": Craftable(
        Name="large boat",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 90.2, "Tailoring": 85.0, "Lumberjacking": 85.0},
        ResourcesNeeded={"boards": 575, "cloth": 100},
        GumpPath=(GumpSelection(carpGump, 64), GumpSelection(carpGump, 30)),
    ),
    "large dragon boat": Craftable(
        Name="large dragon boat",
        Item=None,
        RetainsMark=False,
        RetainsColor=True,
        MinSkill={"Carpentry": 93.5, "Tailoring": 85.0, "Lumberjacking": 85.0},
        ResourcesNeeded={"boards": 600, "cloth": 100},
        GumpPath=(GumpSelection(carpGump, 64), GumpSelection(carpGump, 37)),
    ),
}
